map alt+a disabled
map alt+e disabled
map alt+, disabled
map alt+o disabled
map alt+p disabled
map alt+n disabled

# map alt+d neighboring_window left
# map alt+n neighboring_window right
# map alt+t neighboring_window up
# map alt+h neighboring_window down

# map alt+enter new_window_with_cwd
# map alt+a new_tab_with_cwd
# map alt+f toggle_layout stack
map alt+w close_window

# map alt+r set_tab_title
# map alt+p previous_tab
# map alt+l next_tab

# map ctrl+e launch --type=overlay --cwd=current nvim
