unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "✅ Config reloaded!"

set -g prefix M-c

set -g base-index 1

set -g pane-border-lines single

# List of plugins
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.config/tmux/plugins/'

 set -g @tpm_plugins '           \
   tmux-plugins/tpm               \
   christoomey/vim-tmux-navigator  \
   uhs-robert/tmux-oasis            \
   trevarj/tmux-open-nvim            \
 '

# -------------
# -- Plugins --
# -------------

# -- vim-tmux-navigator -- 
set -g @vim_navigator_mapping_left "C-d" 
set -g @vim_navigator_mapping_down "C-h"
set -g @vim_navigator_mapping_up "C-t"
set -g @vim_navigator_mapping_right "C-n"


# -- theme --
set-option -g status-position top
# set -Fg 'status-format[1]' '#{status-format[0]}'
set -g 'status-format[1]' ''
set -g status 2

set -g @oasis_flavor "lagoon_dark"  # Optional: defaults to lagoon_dark

# -- tmux-open-nvim
set -g @ton-open-strategy ":e"

# ------------
# -- Custom --
# ------------
bind-key w kill-pane

bind-key n split-window -h -c "#{pane_current_path}"
bind-key h split-window -v -c "#{pane_current_path}"

bind-key e run-shell "cd #{pane_current_path}; ~/.config/tmux/plugins/tmux-open-nvim/scripts/ton ."

set -g mouse on

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'

set -g status-style "bg=default,fg=#a9b1d6"
set -g pane-border-style "fg=#3d59a1,bg=default"
set -g pane-active-border-style "fg=#7aa2f7,bg=default"
